language: c

os: linux
dist: trusty

notifications:
  email:
    on_success: change
    on_failure: always

env:
  matrix:
  - BUILD_TYPE=checkpatch
  - BUILD_TYPE=dtb_build_test
  - DEFCONFIG_NAME=zynq_xcomm_adv7511_defconfig ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-
    DTS_FILES=arch/arm/boot/dts/zynq-*.dts IMAGE=uImage
  - DEFCONFIG_NAME=zynq_pluto_defconfig ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-
    DTS_FILES=arch/arm/boot/dts/zynq-*.dts IMAGE=uImage
  - DEFCONFIG_NAME=zynq_sidekiqz2_defconfig ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-
    DTS_FILES=arch/arm/boot/dts/zynq-*.dts IMAGE=uImage
  - DEFCONFIG_NAME=adi_zynqmp_defconfig ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-
    DTS_FILES=arch/arm64/boot/dts/xilinx/zynqmp-*.dts DTS_PREFIX=xilinx/ IMAGE=Image
  - BUILD_TYPE=compile_test DEFCONFIG_NAME=zynq_xcomm_adv7511_defconfig ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-
  - BUILD_TYPE=compile_test DEFCONFIG_NAME=adi_zynqmp_defconfig ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential bc u-boot-tools gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu

script:
  - ./ci/travis/run-build.sh
