# SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause)
%YAML 1.2
---
$id: http://devicetree.org/schemas/soc/adi/adi,pads-system-config.yaml#
$schema: http://devicetree.org/meta-schemas/core.yaml#

title: Analog Devices PADS-related system config for SC5XX processor family

maintainers:
  - Arturs Artamonovs <arturs.artamonovs@analog.com>
  - Utsav Agarwal <Utsav.Agarwal@analog.com>

description:
  Allows other drivers to control the PADS-related system config register.
  This register ties into many drivers and adds silicon controls for items
  like voltage selection and endian selection.

properties:
  compatible:
    enum:
      - adi,pads-system-config

  reg:
    maxItems: 1

required:
  - compatible
  - reg

additionalProperties: false

examples:
  - |
    bus {
      compatible = "simple-bus";
      #address-cells = <1>;
      #size-cells = <1>;
      ranges;

      pads_system_config: adi-control@31004600 {
        compatible = "adi,pads-system-config";
        reg = <0x31004600 0x100>;
      };
    };

    emac0: ethernet@31040000 {
      reg = <0x31040000 0x2000>;
      adi,system-config = <&pads_system_config>;
    };
